# New versions need open_memstream
# which is supported in 10.13 and later
macos_min_version:             # [osx and x86_64]
  - 10.13                      # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - 10.13                      # [osx and x86_64]
