# New versions need open_memstream
# which is supported in 10.13 and later
macos_min_version:             # [osx and x86_64]
  - 10.13                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.13                      # [osx and x86_64]

c_stdlib_version:   # [linux]
  - "2.17"          # [linux]
