{% set name = "mesaLib" %}
{% set version = "18.0.2" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.gz
  sha256: ffd8dfe3337b474a3baa085f0e7ef1a32c7cdc3bed1ad810b2633919a9324840

build:
  skip: True  # [win or py3k]
  number: 0
  track_features:
      - mesalib

requirements:
  build:
      - pthread-stubs
      - pkgconfig
      - toolchain
      - llvmdev
      - expat
  run:
      - pthread-stubs
      - llvmdev
      - expat

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32.so      # [linux]
      - test -f $PREFIX/lib/libOSMesa32.dylib   # [osx]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification, a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - dnadeau4
      - doutriaux1
      - sankhesh
      - danlipsa
