{% set name = "mesaLib" %}
{% set version = "18.3.1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.gz
  sha256: 256d0c3d88e380c1b8e3fc5c6ac34001e3b7c30458b8b852407ec68b8ccd9fda

build:
  skip: True  # [win]
  number: 0
  track_features:
      - mesalib

requirements:
  build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - pkg-config
      - python 2.*
      - mako
      - zlib
      - llvmdev
  host:
      - pthread-stubs
      - expat
      - zlib

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32${SHLIB_EXT}  # [unix]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - dnadeau4
      - doutriaux1
      - sankhesh
      - danlipsa
