{% set name = "mesaLib" %}
{% set version = "17.2.0" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.gz
  sha256: 9484ad96b4bb6cda5bbf1aef52dfa35183dc21aa6258a2991c245996c2fdaf85

build:
  skip: True  # [win or py3k]
  number: 0
  track_features:
      - mesalib

requirements:
  build:
      - pthread-stubs
      - pkgconfig
      - toolchain
      - llvmdev
  run:
      - pthread-stubs
      - llvmdev

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32.so      # [linux]
      - test -f $PREFIX/lib/libOSMesa32.dylib   # [osx]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - dnadeau4
      - doutriaux1
      - sankhesh
      - danlipsa
