{% set name = "mesaLib" %}
{% set version = "24.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: 4ea18b1155a4544a09f7361848974768f6f73c19d88f63de2ec650be313b2d0c

build:
  skip: true  # [win]
  number: 0

  track_features:
    - mesalib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - meson
    - pyyaml
    - mako
    - flex
    - bison
    - pkg-config
    - llvm          # [linux]
    - llvmdev       # [build_platform != target_platform and linux]
  host:
    - expat
    - zlib
    - zstd
    - libdrm                       # [linux]
    - elfutils                     # [linux]
    - ncurses
    - llvm     # [linux]
    - llvmdev  # [linux]
    - libxcb
    - xorg-libx11
    - xorg-libxext
    - xorg-xextproto
    - xorg-xf86vidmodeproto
    - xorg-libxrandr
    - xorg-libxfixes
    - xorg-glproto
    - xorg-libxdamage
    - xorg-xproto      # [linux]
    - xorg-libxxf86vm  # [linux]

  run:
    - xorg-libx11
    - xorg-libxext
    - xorg-xextproto
    - xorg-xf86vidmodeproto
    - xorg-libxrandr
    - xorg-libxfixes
    - xorg-glproto
    - xorg-libxdamage


test:
  requires:
    - pkg-config
  commands:
    # We assert that we didn't build screen rendering capabilities.
    # We want on-screen rendering capabilities to be hardware accelerated
    # but that will take more effort
    - test ! -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/dri/swrast_dri${SHLIB_EXT}      # [linux]
    - test ! -f $PREFIX/lib/libgbm${SHLIB_EXT}              # [linux]
    - test ! -f $PREFIX/lib/libGLESv1_CM${SHLIB_EXT}        # [linux]
    - test ! -f $PREFIX/lib/libGLESv2${SHLIB_EXT}           # [linux]
    - test ! -f $PREFIX/lib/libEGL${SHLIB_EXT}              # [linux]
    - test ! -f $PREFIX/lib/libGL${SHLIB_EXT}               # [linux]
    - test -f $PREFIX/lib/libOSMesa${SHLIB_EXT}           # [linux]
    - test -f $PREFIX/lib/libglapi${SHLIB_EXT}            # [linux]

    - test ! -f $PREFIX/lib/libGLESv1_CM.1${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGLESv2.2${SHLIB_EXT}     # [osx]
    - test -f $PREFIX/lib/libOSMesa.8${SHLIB_EXT}     # [osx]
    - test ! -f $PREFIX/lib/libGL.1${SHLIB_EXT}         # [osx]
    - test -f $PREFIX/lib/libglapi.0${SHLIB_EXT}      # [osx]

    # - pkg-config --exists glesv1_cm
    # - pkg-config --exists glesv2
    - pkg-config --exists osmesa
    # - pkg-config --exists gl
    # - pkg-config --exists egl
    # - pkg-config --exists gbm       # [linux]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener
