{% set name = "mesalib" %}
{% set version = "20.0.4" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.xz
  sha256: c4ed491517a94118a7a611810eeb92645d42ffd82280dcd51be8cc2ba1aabba5

build:
  skip: True  # [win]
  number: 0
  # Do we still need this???? - hmaarrfk - 18.0.0 -- April 2020
  track_features:
      - mesalib

requirements:
  build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - pkg-config
      # still too hard to get rid of python2
      - python 2
      - mako
      - zlib
      - make
  host:
      - pthread-stubs
      - llvmdev
      - expat
      - zlib

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32${SHLIB_EXT}  # [unix]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - dnadeau4
      - doutriaux1
      - sankhesh
      - danlipsa
      - hmaarrfk
      - muryanto1
      - downiec
