{% set name = "mesaLib" %}
{% set version = "20.1.4" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.xz
  sha256: 6800271c2be2a0447510eb4e9b67edd9521859a4d565310617c4b359eb6799fe
  patches:
    - 0001_syscall_kcmp.patch

build:
  skip: True  # [win]
  number: {{ build }}

  track_features:
    - mesalib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libxxf86vm-devel') }}
    - {{ cdt('libxshmfence-devel') }}
    - meson
    - mako
    - flex
    - bison
    - pkg-config

  host:
    - expat
    - zlib
    - libdrm                       # [linux]
    - elfutils                     # [linux]
    - ncurses
    - llvmdev
    - xorg-libx11
    - xorg-libxcb
    - xorg-libxext
    - xorg-xextproto
    - xorg-glproto
    - xorg-xf86vidmodeproto
    - xorg-libxdamage
    - xorg-libxrandr               # [osx]
    - xorg-libxfixes

  run:
    - xorg-libx11
    - xorg-libxcb
    - xorg-libxext
    - xorg-xextproto
    - xorg-glproto
    - xorg-xf86vidmodeproto
    - xorg-libxdamage              # [linux]
    - xorg-libxfixes

  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - pkg-config

  commands:
    - test -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/dri/swrast_dri${SHLIB_EXT}      # [linux]
    - test -f $PREFIX/lib/libgbm${SHLIB_EXT}              # [linux]
    - test -f $PREFIX/lib/libGLESv1_CM${SHLIB_EXT}        # [linux]
    - test -f $PREFIX/lib/libGLESv2${SHLIB_EXT}           # [linux]
    - test -f $PREFIX/lib/libEGL${SHLIB_EXT}              # [linux]
    - test -f $PREFIX/lib/libGL${SHLIB_EXT}               # [linux]
    - test -f $PREFIX/lib/libOSMesa${SHLIB_EXT}           # [linux]
    - test -f $PREFIX/lib/libglapi${SHLIB_EXT}            # [linux]

    - test -f $PREFIX/lib/libGLESv1_CM.1${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libGLESv2.2${SHLIB_EXT}     # [osx]
    - test -f $PREFIX/lib/libOSMesa.8${SHLIB_EXT}     # [osx]
    - test -f $PREFIX/lib/libGL.1${SHLIB_EXT}         # [osx]
    - test -f $PREFIX/lib/libglapi.0${SHLIB_EXT}      # [osx]

    - pkg-config --exists glesv1_cm
    - pkg-config --exists glesv2
    - pkg-config --exists osmesa
    # Disable gl, egl for linux, issue with xxf86vm missing dependency, disbale OpenGL?
    - pkg-config --exists gl        # [osx]
    # - pkg-config --exists egl
    - pkg-config --exists gbm       # [linux]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - sankhesh
      - danlipsa
      - hmaarrfk
      - muryanto1
      - downiec
      - jasonb5
