{% set name = "mesaLib" %}
{% set version = "17.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.gz
  sha256: f82fbbdf2dcec0e7e5aa3a8fe4bacd50bf4b7293cc6e1a56658ae6504d732362

build:
  skip: True  # [win or py3k]
  number: 0
  track_features:
      - mesalib

requirements:
  build:
      - pthread-stubs
      - pkgconfig
      - gcc  # [linux]
      - llvm
      - toolchain
  run:
      - pthread-stubs
      - libgcc  # [linux]
      - llvm

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32.so      # [linux]
      - test -f $PREFIX/lib/libOSMesa32.dylib   # [osx]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - dnadeau4
      - doutriaux1
      - sankhesh
      - danlipsa
