{% set name = "mesaLib" %}
{% set version = "18.0.0" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.gz
  sha256: 93c2d3504b2871ac2146603fb1270f341d36a39695e2950a469c5eac74f98457
  patches:
    # https://patchwork.freedesktop.org/patch/214086/
    - 1-1-gallivm-Fix-build-after-llvm-r328839.patch

build:
  skip: True  # [win]
  number: 1
  # Do we still need this???? - hmaarrfk - 18.0.0 -- April 2020
  track_features:
      - mesalib

requirements:
  build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - pkg-config
      # still too hard to get rid of python2
      - python 2
      - mako
      - zlib
      - make
  host:
      - pthread-stubs
      - llvmdev
      - expat
      - zlib
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32${SHLIB_EXT}  # [unix]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - dnadeau4
      - doutriaux1
      - sankhesh
      - danlipsa
      - hmaarrfk
      - muryanto1
      - downiec
      - jasonb5
