{% set version = "25.0.2" %}

package:
  name: mesalib
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: adf904d083b308df95898600ffed435f4b5c600d95fb6ec6d4c45638627fdc97

build:
  skip: true  # [win]
  number: 0

  track_features:
    - mesalib
  run_exports:
    - {{ pin_subpackage('mesalib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - meson
    - pyyaml
    - mako
    - flex
    - bison
    - pkg-config
    - llvm
    - llvmdev       # [build_platform != target_platform]
    - jq
  host:
    - expat
    - zlib
    - zstd
    - libdrm                       # [linux]
    - elfutils                     # [linux]
    - glslang                      # [linux]
    - ncurses
    - llvm
    - llvmdev
    - libxcb
    - xorg-libx11
    - xorg-libxext
    - xorg-xorgproto
    - xorg-libxrandr
    - xorg-libxfixes
    - xorg-libxdamage
    - xorg-libxxf86vm    # [linux]
    - xorg-libxshmfence  # [linux]

test:
  requires:
    - pkg-config
  commands:
    # We assert that we didn't build screen rendering capabilities.
    # We want on-screen rendering capabilities to be hardware accelerated
    # but that will take more effort
    - test ! -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}    # [linux]
    - test ! -f $PREFIX/lib/dri/swrast_dri${SHLIB_EXT}        # [linux]
    - test ! -f $PREFIX/lib/libgbm${SHLIB_EXT}                # [linux]
    - test ! -f $PREFIX/lib/libGLESv1_CM${SHLIB_EXT}          # [linux]
    - test ! -f $PREFIX/lib/libGLESv2${SHLIB_EXT}             # [linux]
    - test ! -f $PREFIX/lib/libEGL${SHLIB_EXT}                # [linux]
    - test ! -f $PREFIX/lib/libGL${SHLIB_EXT}                 # [linux]
    - test -f $PREFIX/lib/libOSMesa${SHLIB_EXT}               # [linux]
    - test -f $PREFIX/lib/libvulkan_lvp${SHLIB_EXT}           # [linux]
    - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.x86_64.json  # [linux]

    - test ! -f $PREFIX/lib/libGLESv1_CM.1${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGLESv2.2${SHLIB_EXT}     # [osx]
    - test -f $PREFIX/lib/libOSMesa.8${SHLIB_EXT}     # [osx]
    - test ! -f $PREFIX/lib/libGL.1${SHLIB_EXT}         # [osx]

    # - pkg-config --exists glesv1_cm
    # - pkg-config --exists glesv2
    - pkg-config --exists osmesa
    # - pkg-config --exists gl
    # - pkg-config --exists egl
    # - pkg-config --exists gbm       # [linux]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener
