{% set name = "mesaLib" %}
{% set version = "17.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.freedesktop.org/pub/mesa/mesa-{{ version }}.tar.gz
  sha256: 8253edf1bdd7b14ab63d5982349143a5c9ac3767f39a63257cc9d7e7d92f60f1

build:
  skip: True  # [win or py3k]
  number: 3
  track_features:
      - mesalib

requirements:
  build:
      - pthread-stubs
      - pkgconfig
      - gcc  # [linux]
      - llvm
      - toolchain
  run:
      - pthread-stubs
      - libgcc  # [linux]
      - llvm

test:
  commands:
      - test -f $PREFIX/lib/libOSMesa32.so      # [linux]
      - test -f $PREFIX/lib/libOSMesa32.dylib   # [osx]

about:
  home: http://www.mesa3d.org
  license: MIT
  license_file: docs/license.html
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.

extra:
    recipe-maintainers:
      - dnadeau4
      - doutriaux1
      - sankhesh
      - danlipsa
