# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZkNBAF3rMWgAPQsC2mxTklPX9+IjOFvP8qf7Fr51qs6GsofLBYpTKcrDDvt72IW5WGPBG8TgaFo6Jas1wQCMiL9RTZLIxon4HTcQ4QXwlOw+YB2L5x2517rveYBTPpYquLCGB0xtFKLgM0ybTl2h38tJWy4C9hbHLEYeaH7P7JPG9eN6UYszH+NciWBkBSONNlyTZYJ2sqPqW76xdchIHfdCj+vh5qGQTvtHAEWDliSd7U4nSlTYskdWv4VAWt1lJePlaklbOnu1ERG97j3YqWx970QdHrGiXW/FitPlCo7gbWAvO0/qB+VGgVjin6s6cQR/qjzGx/Q2moAxmLPTEfGjUXpVR9XYyNMJNpd47hk6u0c8ggA+7u/dqGmbIDGJPaBuz0cZX5rTFQv7kNU4AyM98f0XjH3Nv+91JyHBpJUOAzkZz3NU1PJ95sDsWCY60jmfSTSxPIwtBwA/MHsoJK1hV5LPUKVwfOEezBpewRaL1xfvusOlqoJp+1VfzqkaU5XLQFSANiAcH+Uw/rQseki1C4EE4qk3rTBNcGR/TnjhoHgZN8aqk6Ngt1aaV8jp5/pwQBbFMPt/Q81eUQdrRM0N274iXa5Yeohrxh/wEK9sHaktH64HHvqYI5GqpGQa7LlTOSPaayc5PwHotgnRDDcK+mG/d+KU7p+17GLglmk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml