# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZkNBAF3rMWgAPQsC2mxTklPX9+IjOFvP8qf7Fr51qs6GsofLBYpTKcrDDvt72IW5WGPBG8TgaFo6Jas1wQCMiL9RTZLIxon4HTcQ4QXwlOw+YB2L5x2517rveYBTPpYquLCGB0xtFKLgM0ybTl2h38tJWy4C9hbHLEYeaH7P7JPG9eN6UYszH+NciWBkBSONNlyTZYJ2sqPqW76xdchIHfdCj+vh5qGQTvtHAEWDliSd7U4nSlTYskdWv4VAWt1lJePlaklbOnu1ERG97j3YqWx970QdHrGiXW/FitPlCo7gbWAvO0/qB+VGgVjin6s6cQR/qjzGx/Q2moAxmLPTEfGjUXpVR9XYyNMJNpd47hk6u0c8ggA+7u/dqGmbIDGJPaBuz0cZX5rTFQv7kNU4AyM98f0XjH3Nv+91JyHBpJUOAzkZz3NU1PJ95sDsWCY60jmfSTSxPIwtBwA/MHsoJK1hV5LPUKVwfOEezBpewRaL1xfvusOlqoJp+1VfzqkaU5XLQFSANiAcH+Uw/rQseki1C4EE4qk3rTBNcGR/TnjhoHgZN8aqk6Ngt1aaV8jp5/pwQBbFMPt/Q81eUQdrRM0N274iXa5Yeohrxh/wEK9sHaktH64HHvqYI5GqpGQa7LlTOSPaayc5PwHotgnRDDcK+mG/d+KU7p+17GLglmk="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi