appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZkNBAF3rMWgAPQsC2mxTklPX9+IjOFvP8qf7Fr51qs6GsofLBYpTKcrDDvt72IW5WGPBG8TgaFo6Jas1wQCMiL9RTZLIxon4HTcQ4QXwlOw+YB2L5x2517rveYBTPpYquLCGB0xtFKLgM0ybTl2h38tJWy4C9hbHLEYeaH7P7JPG9eN6UYszH+NciWBkBSONNlyTZYJ2sqPqW76xdchIHfdCj+vh5qGQTvtHAEWDliSd7U4nSlTYskdWv4VAWt1lJePlaklbOnu1ERG97j3YqWx970QdHrGiXW/FitPlCo7gbWAvO0/qB+VGgVjin6s6cQR/qjzGx/Q2moAxmLPTEfGjUXpVR9XYyNMJNpd47hk6u0c8ggA+7u/dqGmbIDGJPaBuz0cZX5rTFQv7kNU4AyM98f0XjH3Nv+91JyHBpJUOAzkZz3NU1PJ95sDsWCY60jmfSTSxPIwtBwA/MHsoJK1hV5LPUKVwfOEezBpewRaL1xfvusOlqoJp+1VfzqkaU5XLQFSANiAcH+Uw/rQseki1C4EE4qk3rTBNcGR/TnjhoHgZN8aqk6Ngt1aaV8jp5/pwQBbFMPt/Q81eUQdrRM0N274iXa5Yeohrxh/wEK9sHaktH64HHvqYI5GqpGQa7LlTOSPaayc5PwHotgnRDDcK+mG/d+KU7p+17GLglmk=}
