provider:
  linux_aarch64: default
  linux_ppc64le: default
conda_forge_output_validation: true
os_version:
  linux_64: cos7
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
